name: 'Sync to GitLab'
description: 'Automatically sync your GitHub repository with GitLab'
branding:
  icon: 'arrow-right'
  color: 'orange'
inputs:
  gitlab_url:
    description: 'The URL of the GitLab repository (e.g., https://gitlab.com/user/repo.git)'
    required: true
  username:
    description: 'Your GitLab username'
    required: true
  gitlab_pat:
    description: 'Your GitLab Personal Access Token with required permissions'
    required: true
  force_push:
    description: 'Whether to force push to GitLab. Defaults to false.'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Validate inputs
      run: |
        errors=()

        if [[ -z "${{ inputs.gitlab_url }}" ]]; then
          errors+=("gitlab_url is not set. Please add GITLAB_URL to your repository secrets.")
        elif [[ ! "${{ inputs.gitlab_url }}" =~ ^https?://[^/]+/.+ ]]; then
          errors+=("gitlab_url format is invalid. Expected: https://gitlab.com/user/repo.git")
        fi

        if [[ -z "${{ inputs.username }}" ]]; then
          errors+=("username is not set. Please add USERNAME to your repository secrets.")
        fi

        if [[ -z "${{ inputs.gitlab_pat }}" ]]; then
          errors+=("gitlab_pat is not set. Please add GITLAB_PAT to your repository secrets.")
        fi

        if [[ ${#errors[@]} -gt 0 ]]; then
          echo "::error::Configuration Error(s):"
          for err in "${errors[@]}"; do
            echo "::error::  - $err"
          done
          echo ""
          echo "To fix this, go to Settings > Secrets and variables > Actions in your GitHub repository."
          exit 1
        fi

        echo "All inputs validated successfully."
      shell: bash
    - name: Push to GitLab
      run: |
        gitlab_repo_url=${{ inputs.gitlab_url }}
        gitlab_repo_url=${gitlab_repo_url#https://}
        gitlab_repo_url_with_credentials="https://${{ inputs.username }}:${{ inputs.gitlab_pat }}@${gitlab_repo_url}"
        git remote add gitlab "$gitlab_repo_url_with_credentials"
        branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        push_command="git push gitlab $branch_name"
        if [[ "${{ inputs.force_push }}" == "true" ]]; then
          push_command="$push_command --force"
        fi
        $push_command
      shell: bash
